baseURL = 'https://kaylacomer.github.io/blog/'
languageCode = 'en-us'
title = 'Forward Error Correction blog'
theme = 'simple-style'

[params]
subtitle = 'GNU Radio project for Google Summer of Code'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'